### ISSUE TITLE
Crashing on anything past 1.21.1?

### ISSUE THREAD

**Issue by WindowsVista-x64** [Chocohead/Not-So-New#25]
I've gotten 1.21.1 to work just fine with this mod, but whenever I try 1.21.2 or 1.21.3, it just crashes after showing a white window.
The only mod I have installed is Not so New, and the Fabric Loader version is 0.15.11.
I'm using the latest version in the releases, 6.15.

Here's the crash log:
[crash-2024-11-13_21.18.19-client.txt](https://github.com/user-attachments/files/17741996/crash-2024-11-13_21.18.19-client.txt)

**Comment by Chocohead** [comment]
I need to make another release, there's been lots of fixes since 6.15, including 1.21.2/3 & Loader 0.16 support.

**Comment by WindowsVista-x64** [comment]
Oh, alright
I was thinking it's something like that

So if I want to use newer versions right now would I just need to try and compile it myself?

**Comment by Chocohead** [comment]
There are periodic builds in-between the releases on the [actions tab](https://github.com/Chocohead/Not-So-New/actions).

The most recent one as an example is [this run](https://github.com/Chocohead/Not-So-New/actions/runs/11761858879#artifacts). At the bottom the Artifacts section has the download for the build. If you download & unzip that, can use the `NotSoNew-6.45.jar` which includes all the fixes since 6.15
